//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Bakéry
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerTable
    {
        public int CustomerId { get; set; }
        public string cusFirstName { get; set; }
        public string cusMidInitial { get; set; }
        public string cusLastName { get; set; }
        public string cusGender { get; set; }
        public string cusTelephone { get; set; }
        public string email { get; set; }
        public string poBox { get; set; }
        public string district { get; set; }
        public string parish { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
