//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Bakéry
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeTable()
        {
            this.LoginTables = new HashSet<LoginTable>();
        }
    
        public int employeeId { get; set; }
        public string empFirstName { get; set; }
        public string empMidInit { get; set; }
        public string empLastName { get; set; }
        public System.DateTime dob { get; set; }
        public string gender { get; set; }
        public string maritalStat { get; set; }
        public string town { get; set; }
        public string poBox { get; set; }
        public string parish { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoginTable> LoginTables { get; set; }
    }
}
