//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Bakéry
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int employeeId { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string gender { get; set; }
        public string maritalStatus { get; set; }
        public string town { get; set; }
        public string poBox { get; set; }
        public string parish { get; set; }
        public string telephone { get; set; }
        public string email { get; set; }
        public System.DateTime dateAdded { get; set; }
        public byte[] employeePic { get; set; }
    }
}
