//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace La_Bakéry
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        public int productCode { get; set; }
        public string productName { get; set; }
        public double productCost { get; set; }
        public byte[] productImage { get; set; }
        public Nullable<System.DateTime> dateCreated { get; set; }
    }
}
